export const CREATE_NODE_PATH = 'HIERARCHY/NODES/CREATE_NODE_PATH';

export const ADD_CHILD = 'HIERARCHY/NODES/ADD_CHILD';
export const REMOVE_CHILD = 'HIERARCHY/NODES/REMOVE_CHILD';
export const ORDER_CHILD = 'HIERARCHY/NODES/ORDER_CHILD';
export const CREATE_NODE = 'HIERARCHY/NODES/CREATE';
export const DELETE_NODE = 'HIERARCHY/NODES/DELETE';
export const UPDATE_NODE = 'HIERARCHY/NODES/UPDATE';
export const CLEAR_NODES = 'HIERARCHY/NODES/CLEAR';
export const MOVE_NODE = 'HIERARCHY/NODES/MOVE';

export const MOVE_NODE_UP = 'HIERARCHY/NODES/MOVE_NODE_UP';
export const MOVE_NODE_DOWN = 'HIERARCHY/NODES/MOVE_NODE_DOWN';
export const INDENT_NODE = 'HIERARCHY/NODES/INDENT_NODE';
export const UNINDENT_NODE = 'HIERARCHY/NODES/UNINDENT_NODE';

export const types = {
  ADD_CHILD,
  CLEAR_NODES,
  CREATE_NODE,
  CREATE_NODE_PATH,
  DELETE_NODE,
  INDENT_NODE,
  MOVE_NODE,
  MOVE_NODE_DOWN,
  MOVE_NODE_UP,
  ORDER_CHILD,
  REMOVE_CHILD,
  UNINDENT_NODE,
  UPDATE_NODE,
};
